# Generated by Django 6.0.2 on 2026-02-05 06:43

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('remarks', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not mentioned', 'not mentioned')], max_length=50)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('math', 'math'), ('Science', 'Science'), ('Social', 'Social')], max_length=200)),
            ],
        ),
    ]
