# Generated by Django 6.0.2 on 2026-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_formstudent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstudent',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
