# Generated by Django 6.0.2 on 2026-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_formstudent_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstudent',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
