# Generated by Django 6.0.2 on 2026-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_formstudent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstudent',
            name='image',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
