# Generated by Django 6.0.2 on 2026-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_alter_formstudent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstudent',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='formstudent',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
